/**
 * Auto-generated helpers for normalizing build references to your wiki-scraped gear DB.
 * Source: missing-rt-tooltips.txt + gear-from-wiki.ts
 */
export const GEAR_NAME_ALIASES: Record<string, string> = {  'Auto-Striking Powersword': 'Auto-Striking Power Sword',
  'Autoguns': 'Autogun',
  'Black Ring of the Inquisition': 'Black Signet of the Inquisition',
  'Bloodrinker Staff': 'Blooddrinker Staff',
  'Bone Shatterer': 'Bone-Shatterer',
  'Chartist Pendant': 'Chartist\',
  'Death World Origin Enforcer Light Carapace': '[Death World Origin] Enforcer Light Carapace',
  'Double Barreled-Shotgun': 'Double-Barreled Shotgun',
  'Double-Barrel Shotgun': 'Double-Barreled Shotgun',
  'Fortress World Origin Tempestus Carapace': '[Fortress World Origin] Tempestus Carapace',
  'Ghosthelm': 'Ghost Helm',
  'Grimoire of the Void': 'Grimoire of Void',
  'Hadd-Pattern-Data-Loom': 'Hadd-Pattern Data-Loom',
  'Hand of Avolius': 'The Hand of Avolius',
  'Heavy Breacher Boots': 'Heavy Breacher\',
  'Hellbrute Horn Trophy': 'Helbrute Horn Trophy',
  'Hive World Origin Voidsmen Armour': '[Hive World Origin] Voidsmen Armour',
  'Lasguns': 'Lasgun',
  'Malpain Shroud': 'Malpian Shroud',
  'Mars-Pattern Bolt Pistol': '[Mars-Pattern] Bolt Pistol',
  'Mars-Pattern Hot Shot LasPistol': '[Mars-Pattern] Hot Shot Laspistol',
  'Mars-Pattern Hot Shot Laspistol': '[Mars-Pattern] Hot Shot Laspistol',
  'Mars-Pattern Thunder Hammer': '[Mars-Pattern] Thunder Hammer',
  'Mezoa-Pattern Astartes Bolt Pistol': '[Mezoa-Pattern] Astartes Bolt Pistol',
  'Mezoa-Pattern Bolt Pistol': '[Mezoa-Pattern] Bolt Pistol',
  'Notes on Weakness': 'Notes on Weaknesses',
  'Precinct Vox Relay': 'Precinct Vox-Relay',
  'Quick Firing Las Pistol': 'Quick-Firing Laspistol',
  'Quick-Fire Las Pistol': 'Quick-Firing Laspistol',
  'Quick-Firing Las Pistol': 'Quick-Firing Laspistol',
  'Relish Anguish': 'Relished Anguish',
  's Boots': 'Battle-Psyker Boots',
  's Cap': 'Commissar\',
  's Footware': 'Psyker\',
  's Light Boots': 'Enforcer Light Boots',
  's Manual': 'Chirurgeon\',
  's Potent': 'Wanderer\',
  's Vox Relay': 'Precinct Vox-Relay',
  'Saint Cognacius Scriptures': 'Saint Cognatius\',
  'Saint Cognatius Scriptures': 'Saint Cognatius\',
  'Self Calibrating Goggles': 'Self-Calibrating Goggles',
  'Sol Pattern Las Pistol': '[Sol Pattern] Laspistol',
  'Sol Pattern Laspistol': '[Sol Pattern] Laspistol',
  'Sol-Pattern Plasma Pistol': '[Sol-Pattern] Plasma Pistol',
  'Swashbuckler Cloak': 'Swashbuckler Coat',
  'Swiftshroud Cloak': 'Swifstshround Cloak',
  'Symphony of Pain': 'Symphony of Pain x2',
  'Tempestus Elite Carapace': '[War World Origin] Tempestus Elite Carapace',
  'Thrice Pioneers Bracers': 'Thrice-Pioneer\',
  'War World Origin Tempestus Elite Carapace': '[War World Origin] Tempestus Elite Carapace',
};

export const MISSING_GEAR_STUBS: Record<string, any> = {
  'adherent_of_mankind': {
    name: 'Adherent of Mankind',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'aeldari_flow': {
    name: 'Aeldari Flow',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'arc_rifle_mindstorm': {
    name: 'Arc Rifle Mindstorm',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'arch_militant_cape': {
    name: 'Arch-Militant Cape',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'armour_of_hidden_promise': {
    name: 'Armour of Hidden Promise',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'armour_of_the_one_star': {
    name: 'Armour of the One Star',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'black_heart_kabalite_armour': {
    name: 'Black Heart Kabalite Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'blade_of_the_blood_hunter': {
    name: 'Blade of the Blood Hunter',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'blessing_of_death': {
    name: 'Blessing of Death',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'blood_hunter': {
    name: 'Blood Hunter',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'blood_ice_gauntlets': {
    name: 'Blood Ice Gauntlets',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'bloodcraver': {
    name: 'Bloodcraver',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'bloodseeker_klaive': {
    name: 'Bloodseeker Klaive',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'bloody_mentor': {
    name: 'Bloody Mentor',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'bonebreaker': {
    name: 'Bonebreaker',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'boots_of_silence': {
    name: 'Boots of Silence',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'breacher_s_armour': {
    name: 'Breacher\'s Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'carnivorous_blade': {
    name: 'Carnivorous Blade',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'chant_of_stagnation': {
    name: 'Chant of Stagnation',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'chorus_of_battle': {
    name: 'Chorus of Battle',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'cloak_of_mercy': {
    name: 'Cloak of Mercy',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'coffinmaker_sledge': {
    name: 'Coffinmaker Sledge',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'coffinmaker_s_sledge': {
    name: 'CoffinMaker\'s Sledge',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'coffinmaker_s_sledge': {
    name: 'Coffinmaker\'s Sledge',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'corruption_eradicator_helmet': {
    name: 'Corruption Eradicator Helmet',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'death_world_enforcer_light_carapace': {
    name: 'Death World Enforcer Light Carapace',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'death_world_origin_enforcer_light_carapace': {
    name: 'Death World Origin Enforcer Light Carapace',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'death_world_origin_enforcer_s_light_carapace': {
    name: 'Death World Origin Enforcer\'s Light Carapace',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'dog_tag': {
    name: 'Dog Tag',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'dog_tags': {
    name: 'Dog Tags',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'executioner_s_gloves': {
    name: 'Executioner\'s Gloves',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'experimental_psy_amplifier': {
    name: 'Experimental Psy-Amplifier',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'fortress_world_origin_armour': {
    name: 'Fortress World Origin Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'fortress_world_origin_tempestus_carapace': {
    name: 'Fortress World Origin Tempestus Carapace',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'ghosthelm': {
    name: 'Ghosthelm',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'gift_of_kurnous': {
    name: 'Gift of Kurnous',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'gloves_of_inevitable_demise': {
    name: 'Gloves of Inevitable Demise',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'grin_of_the_iron_wolf': {
    name: 'Grin of the Iron Wolf',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'gunslinger_s_helm': {
    name: 'Gunslinger\'s Helm',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'heart_piercer': {
    name: 'Heart Piercer',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'heavy_maul': {
    name: 'Heavy Maul',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'high_spinner_armour': {
    name: 'High Spinner Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'hive_world_origin_voidsman_s_armour': {
    name: 'Hive World Origin Voidsman\'s Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'hive_world_origin_voidsmen_armour': {
    name: 'Hive World Origin Voidsmen Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'hive_world_voidsmen_armour': {
    name: 'Hive World Voidsmen Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'hiveworld_voidsman_armour': {
    name: 'Hiveworld Voidsman Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'holy_power_armour': {
    name: 'Holy Power Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'icebreaker_sabatons': {
    name: 'Icebreaker Sabatons',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'imminent_torment': {
    name: 'Imminent Torment',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'impulse_boots': {
    name: 'Impulse Boots',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'inertia_boots': {
    name: 'Inertia Boots',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'interrogator_knife': {
    name: 'Interrogator Knife',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'invincible_onslaught_armour': {
    name: 'Invincible Onslaught Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'khaine_s_revenge': {
    name: 'Khaine\'s Revenge',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'lady_theodora_s_mantle': {
    name: 'Lady Theodora\'s Mantle',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'lingering_whisper': {
    name: 'Lingering Whisper',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'low_damage_pistol_options_for_at_all_costs': {
    name: 'Low damage pistol options for At All Costs',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'lullaby_of_sha_eil': {
    name: 'Lullaby of Sha\'eil',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'marksman_bracers': {
    name: 'Marksman Bracers',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'marksman_gloves': {
    name: 'Marksman Gloves',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'mars_pattern_bolt_pistol': {
    name: 'Mars-Pattern Bolt Pistol',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'mars_pattern_hot_shot_laspistol': {
    name: 'Mars-Pattern Hot Shot LasPistol',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'mars_pattern_hot_shot_laspistol': {
    name: 'Mars-Pattern Hot Shot Laspistol',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'mars_pattern_thunder_hammer': {
    name: 'Mars-Pattern Thunder Hammer',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'mezoa_pattern_astartes_bolt_pistol': {
    name: 'Mezoa-Pattern Astartes Bolt Pistol',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'mezoa_pattern_bolt_pistol': {
    name: 'Mezoa-Pattern Bolt Pistol',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'might_of_fenris_armour': {
    name: 'Might of Fenris Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'mjodlner': {
    name: 'Mjodlner',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'one_star_power_armour': {
    name: 'One Star Power Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'plasma_pistol_with_cryo_module': {
    name: 'Plasma Pistol with Cryo-Module',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'red_wolf_skull': {
    name: 'Red Wolf Skull',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'riposte_gauntlets': {
    name: 'Riposte Gauntlets',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'ruby_splash': {
    name: 'Ruby Splash',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'ruby_splash_necklace': {
    name: 'Ruby Splash Necklace',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'sanguine_judgement': {
    name: 'Sanguine Judgement',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'scoped_shotgun': {
    name: 'Scoped Shotgun',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'self_calibrating_goggles': {
    name: 'Self Calibrating Goggles',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'sensory_motor_module': {
    name: 'Sensory Motor Module',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'shadow_of_the_undying_one': {
    name: 'Shadow of the Undying One',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'singed_cape': {
    name: 'Singed Cape',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'skitarii_ranger_armour': {
    name: 'Skitarii Ranger Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'slithering_slaughter': {
    name: 'Slithering Slaughter',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'slow_march_of_death': {
    name: 'Slow March of Death',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'snipers': {
    name: 'Snipers',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'sol_elite_power_sword': {
    name: 'Sol Elite Power Sword',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'sol_pattern_las_pistol': {
    name: 'Sol Pattern Las Pistol',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'sol_pattern_laspistol': {
    name: 'Sol Pattern Laspistol',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'sol_pattern_shotgun': {
    name: 'Sol Pattern Shotgun',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'sol_pattern_plasma_pistol': {
    name: 'Sol-Pattern Plasma Pistol',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'sol_pattern_shotgun': {
    name: 'Sol-Pattern Shotgun',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'solid_shield_enarmes': {
    name: 'Solid Shield Enarmes',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'sturdy_shield_straps': {
    name: 'Sturdy Shield Straps',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'suffering_collector': {
    name: 'Suffering Collector',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'synaptic_coagulator': {
    name: 'Synaptic Coagulator',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'tactica_imperialis_excerpt': {
    name: 'Tactica Imperialis Excerpt',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'tempestus_elite_carapace_backpack': {
    name: 'Tempestus Elite Carapace Backpack',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'thassertium_mask': {
    name: 'Thassertium Mask',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'thassertium_necklace': {
    name: 'Thassertium Necklace',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'the_hunter_father_s_armour': {
    name: 'The Hunter-Father\'s Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'triumph_of_faith': {
    name: 'Triumph of Faith',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'typhoon': {
    name: 'Typhoon',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'war_world_origin_armour': {
    name: 'War World Origin Armour',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'war_world_origin_tempestus_elite_carapace': {
    name: 'War World Origin Tempestus Elite Carapace',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'well_maintained_rock_saw': {
    name: 'Well-Maintained Rock Saw',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'well_maintained_rocksaw': {
    name: 'Well-Maintained Rocksaw',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'wrathful_mask': {
    name: 'Wrathful Mask',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
  'wytch_s_last_cry': {
    name: 'Wytch\'s Last Cry',
    type: 'unknown',
    effect: '',
    stats: {},
    wikiUrl: '',
  },
};

// Quick normalizer (match your pipeline as needed)
export function normalizeName(s: string): string {
  return s
    .toLowerCase()
    .replace(/\[[^\]]*\]/g, '')          // remove [tags]
    .replace(/[’]/g, "'")
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .replace(/\s+/g, ' ');
}
